name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  compile_and_verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Install cairo-listings
        run: cargo install --path cairo-listings --locked
        shell: bash

      - name: Run cairo-listings and generate summary
        run: cairo-listings -- verify >> $GITHUB_STEP_SUMMARY
        shell: bash

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
